import type { Metadata } from "next";
import { Geist, Geist_Mono, Fjalla_One, Actor } from "next/font/google";
import "./globals.css";
import TopNavbar from "./components/TopNavbar";

 const fjalla = Fjalla_One({
   variable: "--font-fjalla-title",
    weight: "400"
 });

 const actor = Actor({
  variable: "--font-actor",
  weight: "400"
 })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Inspirational Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fjalla.variable} ${actor.variable} antialiased`}
      >
        <TopNavbar/>
        {children}
      </body>
    </html>
  );
}
